//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagerReponsity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Room_Bookings = new HashSet<Room_Bookings>();
        }
    
        public int RoomNumber { get; set; }
        public string nameRoom { get; set; }
        public Nullable<int> RoomStatus_id { get; set; }
        public Nullable<int> RoomType_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room_Bookings> Room_Bookings { get; set; }
        public virtual Room_Status Room_Status { get; set; }
        public virtual Room_Type Room_Type { get; set; }
    }
}
