//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagerReponsity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Bookings
    {
        public Nullable<System.DateTime> date_booking_from { get; set; }
        public Nullable<System.DateTime> date_booking_to { get; set; }
        public Nullable<int> room_cout { get; set; }
        public int idBooking { get; set; }
        public int Room_id { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Room Room { get; set; }
    }
}
